# GoLeash Configuration

# Target binaries to monitor
[targets]
#binaries = [
#  "frpc",
#  "frps"
#]
#binary_paths = [
#  "../exp1/frp/target/bin/frps",
#  "../exp1/frp/target/bin/frpc"
#]

#binaries = [
#  "geth"
#]
#binary_paths = [
#  "../exp1/go-ethereum/geth"
#]

#binaries = [
#  "coredns"
#]

#binary_paths = [
#  "../exp1/coredns/target/coredns"
#]

#binaries = [
#  "etcd"
#  "etcdctl"
#  "etcdutl"
#]
#binary_paths = [
#  "../exp1/etcd/target/bin/etcd"
#  "../exp1/etcd/target/bin/etcdctl"
#  "../exp1/etcd/target/bin/etcdutl"
#]

binaries = [
  "kube-apiserver",
  "kube-controller",
  "kube-scheduler",
  "kube-proxy",
  "kubelet",
  "kubectl"
]
#binary_paths = [
#  "/home/debian/kubefence_workspace/kubernetes/_output/local/go/bin/kube-apiserver",
#  "/home/debian/kubefence_workspace/kubernetes/_output/local/go/bin/kube-controller-manager",
#  "/home/debian/kubefence_workspace/kubernetes/_output/local/go/bin/kube-scheduler",
#  "/home/debian/kubefence_workspace/kubernetes/_output/local/go/bin/kube-proxy",
#  "/home/debian/kubefence_workspace/kubernetes/_output/local/go/bin/kubelet",
#  "/home/debian/kubefence_workspace/kubernetes/_output/local/go/bin/kubectl"
#]

binary_paths = [
  "/usr/bin/kube-apiserver",
  "/usr/bin/kube-controller",
  "/usr/bin/kube-scheduler",
  "/usr/bin/kube-proxy",
  "/usr/bin/kubelet",
  "/usr/bin/kubectl"
]
#binaries = [
#  "testExec"
#]
#binary_paths = [
#  "../testPkgs/testExec/testExec"
#]

#binaries = [
#  "testMalicious"
#]
#binary_paths = [
#  "../exp1/testMalicious/target/testMalicious"
#]












